## Project Workshop 1
### Created by Sophia Yuhaniz

In [34]:
# 3. import numpy as np
import numpy as np

In [7]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
matriks = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
matriks

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# 5.What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [9]:
# 6. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\user pc\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app


False

In [27]:
# 7. Create a random vector of size 30 and find the mean value

v =np.random.rand(30)
v
meanv = np.mean(v)
meanv


0.44641224669100832

In [43]:
# 8/9. Multiply 5x3 matrix by a 3 x 2 matrix

x = np.ones((5,3))
y = np.ones((3,2))
results = np.matmul(x,y)
results

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [44]:
# 10. Create a random vector of size 10 and sort it
v =np.random.rand(10)
np.sort(v)

array([ 0.29983626,  0.32504814,  0.43076455,  0.49035324,  0.4957694 ,
        0.54708273,  0.74632313,  0.87790541,  0.88347541,  0.89150926])

In [52]:
# 11. Create a random of size 100 and replace the maximum value by 0
v =np.random.rand(100)
v[np.where(v == v.max())]=0

In [53]:
# 12. How to get the diagonal of a dot product?
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)
np.diag(np.dot(np.dot(a, b), a.T))

array([  60,  672, 1932, 3840, 6396])